# This is a basic workflow to help you get started with Actions

name: AutoSign

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '03 13 * * *'


# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    name: Python ${{matrix.python-version}} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: 'Install requirements'
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: 'Sign'
        env:
          USER_ACCOUNT: ${{ secrets.USER_ACCOUNT }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          USER_LOCATIN: ${{ secrets.USER_LOCATIN }}
          USER_COORDINATES: ${{ secrets.USER_COORDINATES }}
        run: 
          python yibanAutoSgin.py
